spring:
  datasource:
    db1:
      #mysql数据源
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2b8
      username: root
      password: yhh
      #password: 123(loptop)/123456(docker)
    db2:
      #phoenix数据源
      driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
      jdbc-url: jdbc:phoenix:hadoop102,hadoop103,hadoop104:2181

  redis:
    host: ubuntu22
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的所有xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql语句